In [1]:
import numpy as np 

for i in range(100):
  
    array = np.random.randint(2, size=(3, 3)) 
    print(array) 

    sumaFila=[sum(i) for i in array]
    print (sumaFila)

    x=0;
    for i in range (len(array)):
        if sumaFila[i]!=0:
            if sumaFila[i]%2 !=0:
                x-=1
            else:
                x+=1      
    if x==len(array):
        print("ES")
    else:
        print("no")
    

[[0 1 1]
 [0 0 1]
 [1 1 1]]
[2, 1, 3]
no
[[1 0 1]
 [1 1 1]
 [1 0 1]]
[2, 3, 2]
no
[[0 1 1]
 [1 1 0]
 [1 1 1]]
[2, 2, 3]
no
[[0 0 0]
 [0 1 0]
 [0 0 0]]
[0, 1, 0]
no
[[1 0 1]
 [0 1 0]
 [1 0 0]]
[2, 1, 1]
no
[[0 0 1]
 [0 0 0]
 [1 0 0]]
[1, 0, 1]
no
[[1 0 1]
 [0 1 0]
 [1 1 1]]
[2, 1, 3]
no
[[0 1 1]
 [0 0 1]
 [1 0 1]]
[2, 1, 2]
no
[[0 0 1]
 [0 0 0]
 [0 1 1]]
[1, 0, 2]
no
[[1 1 1]
 [0 0 0]
 [1 0 0]]
[3, 0, 1]
no
[[1 1 1]
 [0 1 0]
 [1 0 0]]
[3, 1, 1]
no
[[1 1 0]
 [0 0 1]
 [1 1 0]]
[2, 1, 2]
no
[[0 1 1]
 [1 1 0]
 [0 1 1]]
[2, 2, 2]
ES
[[0 0 0]
 [1 1 1]
 [0 0 0]]
[0, 3, 0]
no
[[1 0 1]
 [0 1 0]
 [0 0 0]]
[2, 1, 0]
no
[[0 1 0]
 [1 1 0]
 [1 1 1]]
[1, 2, 3]
no
[[1 1 1]
 [1 1 0]
 [1 0 1]]
[3, 2, 2]
no
[[1 1 1]
 [0 1 0]
 [1 1 0]]
[3, 1, 2]
no
[[1 0 1]
 [1 0 0]
 [1 1 0]]
[2, 1, 2]
no
[[1 0 1]
 [0 0 1]
 [1 1 0]]
[2, 1, 2]
no
[[0 0 1]
 [1 1 0]
 [1 0 1]]
[1, 2, 2]
no
[[1 0 0]
 [1 0 0]
 [1 0 0]]
[1, 1, 1]
no
[[0 1 1]
 [0 1 0]
 [0 1 1]]
[2, 1, 2]
no
[[0 0 1]
 [0 0 1]
 [1 0 0]]
[1, 1, 1]
no
[[1 1 0]
 [1 0 0

In [ ]:
import numpy as np 

for i in range(100):
  
    array = np.random.randint(2, size=(3, 3)) 
    print(array) 

    sumaFila=[sum(i) for i in array]
    print (sumaFila)

    x=0;
    for i in range (len(array)):
        if sumaFila[i]!=0:
            if sumaFila[i]%2 !=0:
                x-=1
            else:
                x+=1      
    if x==len(array):
        print("ES")
    else:
        print("no")